services:
  # 1. Nosso serviço de banco de dados
  db:
    image: postgres:15
    container_name: matricula_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=matricula_facil_db
    restart: always

  # 2. Nosso serviço Back-end (Java/Spring Boot)
  backend:
    build: . # Procura o Dockerfile na mesma pasta
    container_name: matricula_backend_container
    ports:
      - "8080:8080" # Abre a porta 8080 do PC
    environment:
      - DB_HOST=db # Avisa o Java que o banco está no container chamado "db"
    depends_on:
      - db # Garante que o banco comece a subir antes do back-end
    restart: always