services:
  db:
    image: postgres:15
    container_name: matricula_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=matricula_facil_db
    restart: always

  backend:
    build: . # Procura o Dockerfile na mesma pasta
    container_name: matricula_backend_container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: always