# Nome do projeto
spring.application.name=matricula_facil

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/matricula_facil_db?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=senha

#JPA (O ORM)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true