# Nome do projeto
spring.application.name=matricula_facil

# Configuracao Dinamica: Se a variavel DB_HOST existir, usa ela. Senao, usa 127.0.0.1.
spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/matricula_facil_db?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=senha

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Forca o dialeto para evitar erros na inicializacao do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect